name: callme from others

on:
  workflow_call:
    inputs:
      # tag to be added to the image
      tag:
        required: false
        type: string
      shared-env:
        type: string
        required: true


jobs:
  deploystage:
    runs-on: ubuntu-latest
    steps:
      - name: test env from before
        run: echo "${{inputs.shared-env}}"